### ISSUE TITLE
Make it easier to use/update nightly configure scripts

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#606] opened 2020-07-02 18:08 UTC
@ikalash Could we collapse the nightly configure scripts and the manual configure scripts into one file (i.e. ctest_nightly_\*.cmake and do-cmake-\*)? I'm sure there's a way to do this but I don't think I know enough about ctest. For example, maybe we can store the configure line for cmake in an environment variable in one file and then just call that file in do-cmake, ctest_nightly.

**Comment by ikalash** [comment] 2020-07-02 18:10
I'm sure one can, but I don't have the time to figure it out now.  You are welcome to give it a try.

**Comment by jewatkins** [comment] 2020-07-02 18:12
Would you be okay with the solution above if it works with your ctest script? It would mean you would have to go to another file to update the configure line.

**Comment by ikalash** [comment] 2020-07-02 19:41
I'm not sure I understand what you are proposing.  If you create scripts and want me to test them, I'm happy to do so.

**Comment by jewatkins** [comment] 2020-07-02 19:50
I'll test it out when it becomes relevant again. We can talk about it later, it's not a huge priority.

**Comment by ikalash** [comment] 2020-07-02 20:01
Ok sounds good.  I think what you are proposing would be a great change to the nightly testing workflow - would certainly simplify creating builds analogous to the nightly test ones using straight-up cmake.

**Comment by ikalash** [comment] 2020-07-30 02:36
I came up with a solution to this, which I have implemented so far for the CEE intel build I created with sems modules.  A regular configure script (https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/cee-compute011.sandia.gov/do-cmake-trilinos-mpi-sems-intel ) lives in the repo.  As part of the nightly testing, I run a script that converts this file into one that is CDash friendly and inserts it into the ctest_nightly.cmake file required by CDash, and this gets run just like before.  One can easily reproduce the nightly build using the do-cmake file in the repo used by the nightlies.  If one wishes to change the nightly behavior, similarly, one just needs to change this file. 

I have not created a similar do-cmake file for Albany b/c I think it's so simple anyway for Albany, that this is overkill.  It could be done so. 

I'll eventually convert the other nightlies to work like the Intel one, once I verify that everything works smoothly.

**Comment by jewatkins** [comment] 2020-07-30 15:20
That's great, that should save me a lot of time trying to make sure I have the correct configuration. I agree, I don't think it's needed for the albany script.

**Comment by ikalash** [comment] 2020-07-30 17:38
Agreed, it should save all of us time.  I will gradually work on transitioning the other nightlies to this approach.  I was able to get a clang build working with the sems modules so that will be the next step.  The nightlies last night confirmed that  the new scripts I wrote are working correctly.

**Comment by ikalash** [comment] 2020-08-02 19:52
I am going to close this, since I implemented my above fix for the CEE, ride, blake and cori nightlies.  I will do it for mayer and weaver once those get re-set up.  The other nightlies do not use the usual CDash scripts so the fix is not relevant.

**Closed by ikalash** 2020-08-02 19:52 UTC
Labels: Testing, build, cmake, developer usability, enhancement

**Comment by mperego** [comment] 2020-08-03 02:52
Hi Irina, this is great. So, if I want to reproduce the issue with the Hessian AD on the cee clang debug built what cmake script should I use? Can I use this
https://github.com/SNLComputation/Albany/blob/master/doc/dashboards/cee-compute011.sandia.gov/do-cmake-trilinos-mpi-sems-clang
and switch the BTYPE to DEBUG>?

**Comment by ikalash** [comment] 2020-08-03 02:59
Exactly!  But please source the relevant modules file first.  Note that for most builds if you want to make a change to the configure script in the nightlies changing it in the repo is not enough - I have to update it on the machine too.   This is for security reasons mostly - so people can't directly control the nightlies just by modifying files in the repo.
