### ISSUE TITLE
Various LandIce fields don't have evaluators error

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#423] opened 2019-01-19 05:09 UTC
It looks like an error involving various LandIce fields not having evaluators cropped up, I think from this commit by @bartgol : https://github.com/SNLComputation/Albany/commit/68be4986aabb165716a751026e3205e8e2f94396 (PR merge).  Here is the error:

http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=80504

It did not get caught until yesterday b/c I had ```-D Phalanx_ALLOW_MULTIPLE_EVALUATORS_FOR_SAME_FIELD:BOOL=OFF``` in the tests, to they were failing for other reasons.

**Comment by ikalash** [comment] 2019-01-29 14:18
@bartgol : your PR did not fix this problem.  Can you please have a look?  Here is a sample of the errors: 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4280623&build=80874 

I am not sure why it is only happening on my workstation camobap.

**Comment by bartgol** [comment] 2019-01-29 16:53
The problem is that you have CISM_LANDICE defined, even if this build will not be used for CISM. This causes StokesFOBase to _not_ evaluate the surface height gradient, since it's assuming it will be probided by CISM. I think you need to change the build, so that you do not enable CISM unless you are installing albany for CISM.

**Comment by ikalash** [comment] 2019-01-29 16:56
I want CISM on in this build though - I am still building / testing CISM-Albany.  Can we make the build work with CISM-Albany enabled?

**Comment by bartgol** [comment] 2019-01-29 17:12
Hold on, then why do we see this warning?

``-- WARNING: cism_driver will not link properly when built if
Albany was built with LCM, LAME, or ENABLE_DEMO_PDES.  Turn these off to build
cism_driver.

Either the warning is wrong (i.e., it's ok to build LCM or DEMO_PDES when building for CISM), or you need to disable something.

**Comment by bartgol** [comment] 2019-01-29 17:31
Anyhow, turns out we can the build work. I'll push a fix.

**Comment by ikalash** [comment] 2019-01-29 19:35
@bartgol : regarding your question about the warning that is printed to screen.  

I am not sure what this was about.  I tracked it down to this commit by me from more than 4 years ago: 

```
commit b06eecfd7cfd2dcfd8a905660acdc88352eb0949
Author: Irina Kalashnikova <ikalash@sandia.gov>
Date:   Fri Oct 24 21:11:23 2014 -0700

    Some fixes to cism_interface in temporary_tpetra_newSTK branch.
    For cism_driver to build correctly on cism (felix_interface) side,
    Albany needs to have LCM, Lame, and Hydride turned off.  Adding a warning
    to be printed if they are on.  Things will still build on the Albany side,
    just not the CISM side.
```

My nightlies definitely have had LCM on, and CISM was building just fine against Albany until this issue cropped up.  I think we can remove the printing of the warning to screen.  Thanks for calling this to my attention, Luca!

**Comment by ikalash** [comment] 2019-01-30 14:35
It looks like the CISM tests are failing still.  I am guessing a similar change to the one you pushed yesterday @bartgol needs to go in ali_driver.cpp?  I am away from a computer now so I can’t look at it right now.

**Comment by mperego** [comment] 2019-01-30 16:23
Looking at the error, it might be an easy fix (it's related to the temperature field but CISM does not use it). However, I think Luca is busy with a deadline this week. I'll try to have a look at that sometime this week if nobody does that before. It's not high priority since at the moment we are not using CISM-Albany.

**Comment by bartgol** [comment] 2019-01-30 20:00
Working on a fix.

**Comment by bartgol** [comment] 2019-01-30 23:39
I belive c74298bd3ec28aaa25d836ad9a2f1ba68cf5a2c9 fixed this. Let's see what CDash has to say tomorrow.

**Comment by bartgol** [comment] 2019-01-31 15:41
Never mind. Last night nightlies still fail.

**Comment by bartgol** [comment] 2019-01-31 16:20
There was an issue with the scalar type of CISM surface gradient. I pushed a fix. Let's see how the nightlies go.

**Comment by bartgol** [comment] 2019-02-01 05:49
Cism tests seem to pass. Closing.

**Closed by bartgol** 2019-02-01 05:49 UTC
Labels: LandIce

**Comment by ikalash** [comment] 2019-02-01 05:52
Yes, tests are good now.  Thanks for fixing them, Luca!
