### ISSUE TITLE
Schwarz Exodus output corrupted after unpetrify merge

### ISSUE THREAD

**Issue by lxmota** [SNLComputation/Albany#482] opened 2019-05-22 00:48 UTC
@bartgol @ikalash The Exodus output files for Schwarz Alternating are corrupted after the merge, and cannot be opened in Paraview.

The tests pass because they check for convergence in the log file, but when trying to open the Exodus files, Paraview says the fields with the solution do not exist.

I tried determining the cause, but it's not obvious to me. Could it be related to STK issues mentioned in #480?

Examples that fail:

`https://github.com/SNLComputation/Albany/tree/master/tests/large/LCM/Schwarz/Alternating/Quasistatics`

`https://github.com/SNLComputation/Albany/tree/master/tests/large/LCM/Schwarz/Alternating/Dynamics/Cubes`

**Comment by bartgol** [comment] 2019-05-22 14:50
Ah! Have you tried to use exotxt and see if you can get a text version of the file? If that works, we can at least try to see what's missing in the file...

**Comment by bartgol** [comment] 2019-05-22 14:52
As I said yesterday, I have O(\epsilon) time for Albany this week. If you can't figure it out, I can pick it up next week (hopefully).

**Comment by ikalash** [comment] 2019-05-31 00:13
@lxmota: I just looked at this and I don't believe it is a bug, actually.  If you do "ncdump cuboid_00.e" on one of the output files, you will see that there are actually 0 time-steps written to the files for whatever reason (likely we're setting the Exodus output frequency to get this outcome):
```
   time_step = UNLIMITED ; // (0 currently)
```
If you run the tests using an older checkout of the branch (I tried 5ad554b53c23156b08db7d6bd129f3e08b9d3820 from end of April), you see the same thing, and you get the same error in Paraview when you try to load the file (a box pops up that says "Could not read nodal output variable disp_x, etc.").   

In contrast, if you run a test where there is >0 snapshots written to the output file (e.g. tests/large/LCM/Schwarz/Alternating/Dynamics/CubesInelastic), the file is right and Paraview can read it.  

Please give it a try to confirm.

**Comment by lxmota** [comment] 2019-05-31 22:26
I have determined that this is a real issue. The problem is this call:

https://github.com/SNLComputation/Albany/blob/master/src/LCM/solvers/Schwarz_Alternating.cpp#L1338

@ikalash says that this may be related to an STK refactor to use Thyra.

**Comment by ikalash** [comment] 2019-05-31 22:28
@bartgol : could you look at this also while I'm away?  The hash I pointed to was from ~1 month ago but it had some of your refactors to STK, and I think likely the culprit is some of those refactors.  Unfortunately the way that the testing goes for the Schwarz tests, we didn't catch the issue until now.

**Comment by bartgol** [comment] 2019-06-03 19:12
Sorry for being off for quite a bit. I will take a look to this today.

**Comment by ikalash** [comment] 2019-06-03 20:52
That would be great - thanks Luca!

**Comment by bartgol** [comment] 2019-06-05 00:10
I did a check on a version of master before the unpetrify merge, namely this commit 268cb8b. The file is corrupted also in that version of Albany, so this is not due to the unpetrify merge, but something else (might still be related to some thyra refactor though, can't tell).

**Comment by ikalash** [comment] 2019-06-05 06:58
Right I said this above.  I believe its due to one of your earlier stk refactors in the fall. End of Aug things were good.  Then something happened in the fall. We weren't working on the code at the time so I'm sure it is related to the refactor.

**Comment by bartgol** [comment] 2019-06-05 17:39
Oh that's the refactor you meant. Sorry, I misread.

Anyhow, I digged a bit, and it seems the meta data of the mesh is corrupted. More precisely, there is no entity group stored in the universal part, which cause the call to `write_defined_output_fields` to do nothing. I have to understand _if_ this is due to changes in Albany or STK. The former case is more likely, but you never know...

**Comment by ikalash** [comment] 2019-06-05 18:16
Yes sorry about the conclusion.  Thanks for looking at it.  What you propose makes sense.  Stk has broken Albany in the past so it’s worth checking that it’s not the case.  I’d apply method of bisecting starting around mid August.

**Comment by bartgol** [comment] 2019-06-10 19:10
Interesting: the corruption happens in release mode but _not_ in debug mode. Not just that: in release mode I only see `disp_` and `resid_` when I open paraview, while in debug mode I see all the `Cauchy_Stress_X_Y` fields. 

Side note: in debug I got a _ton_ of undeleted RCP objects at the end (about 4k RCP's). I _think_ they were related to the Schwarz implementation, and its handling of multiple apps (with all the RCP's contained in them). Other tests do not show these dangling RCPs. Most likely explanation is a circular dependency hidden somewhere in `Schwarz_Alternating.*pp`. I have no idea where though, I tried to debug, and got nowhere.

**Comment by bartgol** [comment] 2019-06-10 21:37
Ah. The file is not corrupted as long as trilinos is compiled in debug mode. I tried to dig into the stk and seacas folders, hunting down the issue, but I came back empty handed.

I can't say for sure whether this is a problem in trilinos or in Albany (we may be giving some wrong inputs to some stk calls). I also don't know if the dangling RCPs are somehow linked to this issue. Unfortunately, I am not sure how to proceed in order to fix this.

**Comment by bartgol** [comment] 2019-06-10 23:35
With a ton of rebuild time, I was able to find two trilinos commits suitable to start bisection. There are about 9 bisection steps left. However, this is a ton of time, given you basically have to rebuild the whole trilinos almost every time (and muelu is already 50% of it anyways), and possibly adjust albany due to interface changes.

Interestingly, the two commits are from 1y ago and 9 months ago. So if stk is indeed to blame for this, the tests in LCM should have had a corrupted output for _quite some time_.

Since this may not be related to what I did in stk (or so it seems, given that trilinos from 1yy ago generates correct exodus files), can I please ask someone from the LCM team to carry on this bisection? The good commit I found was 71d7346, and the bad one was be6a126.

**Comment by lxmota** [comment] 2019-06-11 17:43
@bartgol @ikalash Thanks Luca for doing this, and for pointing out the RCP issues. One more reason I dislike them so much.

**Comment by bartgol** [comment] 2019-06-11 19:05
@lxmota to be fair, it's not likely to be the RCP's fault. _Somewhere_ someone is doing something wrong (e.g., extract raw pointer and assigning it to another strong RCP).

One thing I _do_ like about RCP is this ability to track undestroyed nodes at exit in debug mode. Sure, valgrind can do that too, but a) you need to run through valgrind (slower), and b) after memory check you still need to figure out which block is used where.

**Comment by ikalash** [comment] 2019-06-17 16:38
@bartgol : thanks for doing this!  It must have taken a lot of time.  

I can take over the bisection from here, sure.  Just to clarify, does Trilinos need to be release?  It seems from what you describe that there are issues in both debug and release, but they are not the same. 

I find it curious that not all the Schwarz tests have this I/O issue - for instance, Alternating/Dynamics/CubesInelastic has normal output as expected.  

I was thinking at some point this might be a problem when not using DTK but I think it is not, as I see the issue on my workstation which has DTK, as does @lxmota .

**Comment by bartgol** [comment] 2019-06-17 20:14
@ikalash on my workstation, the output was not corrupted in debug mode, but it was corrupted in release mode. In particular, in release mode, the output contained the correct headers (geometry info, and number/name of exported variables), but no exported time steps. Albany _does_ call the proper methods in the stk interface, but for some reason, stuff does not get written to the file.

The RCP issue may as well be there in release mode as well, but we can't tell, cause the RCP trace system is only active in a debug trilinos build.

**Comment by ikalash** [comment] 2019-06-18 23:58
In the nightlies, I also see that the files are OK in my debug build.  I wonder what happens in a partial debug build (release Trilinos and debug Albany).

**Comment by bartgol** [comment] 2019-06-19 14:38
I tried release Trilinos and debug albany and the files are corrupted. It seems to be a different behavior when _Triliinos_ is build in either debug or release mode.

**Comment by ikalash** [comment] 2019-06-19 17:33
@bartgol : did you encounter the following error when building Albany against the older Trilinos?

```
[ 49%] Built target albanyLib
/usr/bin/ld: warning: libmpi.so.12, needed by /usr/local/netcdf/lib/libnetcdf.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/ikalash/schwarzOutputDebug/Trilinos_good/build/install/lib/libmuelu.so.12.13: undefined reference to `MueLu::MpiTypeTraits<unsigned long>::getType()'
collect2: error: ld returned 1 exit status
```
I am getting this error and can't quite figure out how to resolve it.

**Comment by bartgol** [comment] 2019-06-19 19:12
No, I didn't, sorry. Did you wipe out the trilinos installation folder? Sometimes I got link errors in Trilinos because I forgot to wipe out the folder and do a fresh install.

**Comment by lxmota** [comment] 2019-06-19 20:06
@ikalash What machine are you using? If camobap, then you need to install the followiing:

netcdf
netcdf-devel
netcdf-openmpi
netcdf-openmpi-devel
netcdf-static

And recompile Trilinos from scratch

**Comment by ikalash** [comment] 2019-06-19 22:24
@bartgol : wiping didn't help, but turning off muelu helped (and greatly sped up the build time).

@lxmota : it's on camobap but the problem is not with netcdf.  I'm trying to build a special branch of Albany against an old Trilinos, and it was causing undefined reference errors in muelu.  I think you're referring to the netcdf warning right above the muelu error that I posed.  I do get that warning on my machine but it is just a warning, not an error, and I haven't tried to fix it b/c I don't want to risk messing things up with the netcdf I have that works.

**Comment by ikalash** [comment] 2019-07-03 00:59
Ok, so I have identified which commit in Trilinos broke the Schwarz output.  It was this one to seacas by Greg Sjaardema on Sept. 7 2018:  12cd80bbbdf88ce3ad2f7b4e7077419bf6d07aa0 .  

```
    Automatic snapshot commit from seacas at 933debf80 (#3406)
    
    Origin repo remote tracking branch: 'origin/master'
    Origin repo remote repo URL: 'origin = https://github.com/gsjaardema/seacas'
    
    At commit:
    
    commit 933debf806affe117bf9992aaabf0e7dfc50c273
    Author:  Greg Sjaardema <gsjaardema@gmail.com>
    Date:    Fri Sep 7 09:01:04 2018 -0600
    Summary: EXODUS: Update version number forgotten in recent changes

```
There are a lot of changes in this commit and it would take me awhile to figure out what is the culprit...  so I propose we open a Trilinos issue.  Hopefully Greg will be willing to look at it - he has been helpful with things like this in the past.  I am pretty convinced that the issue is on the Trilinos side not the Albany side since the Albany I was using in my bisection exercise was effectively VOTD from now (with a few minor changes to get the code to compile with an older Trilinos).

**Comment by ikalash** [comment] 2019-07-04 06:12
FYI: I opened a Trilinos issue on this 

https://github.com/trilinos/Trilinos/issues/5479

**Comment by ikalash** [comment] 2019-08-16 18:26
This issue has been resolved.  Requires the following Trilinos PR which was merged in recently: https://github.com/trilinos/Trilinos/pull/5667 .  Please see https://github.com/trilinos/Trilinos/issues/5479 for more discussion on what was the problem.

**Closed by ikalash** 2019-08-16 18:26 UTC
Labels: LCM, STK
