### ISSUE TITLE
Creep Model Issues with Linear and Non-Linear Solver Convergence from Buckling

### ISSUE THREAD

**Issue by JustinClough** [SNLComputation/Albany#536] opened 2019-11-13 23:23 UTC
Following up from yesterday's phone call:

I'm having issues with using the creep model in Albany. I have a rectangular plate that is fixed on two opposite ends in all directions and has a prescribed uniform linear temperature increase with time. All my inputs files (`input.yaml`, `material.yaml`, and `plate.msh`) are attached for reference in the zip file. I'm also using the composite tet10 elements in the mesh.

My issue is that after "turning off" both nonlinear parts of the creep model by giving both a high yield stress and creep activation temperature, the non-linear solver still eventually fails. (The non-linear solver *also* fails with realistic yield stresses and activation temperatures for my material but I figured simplifying the problem would help show the root issues.) Specifically, the non-linear solver returns increasingly large residuals, eventually `-nan`, and then throws a `Thyra::CatastrophicSolveFailure`. A copy of the output is in `output.txt` in the zip file.

I'm looking for help understanding what's going on in a few ways:
1. With yielding and creep "turned off", the model simplifies to linear thermo-elasticity. Also, the mesh is relatively small (~6,000 DOFs). Why do the linear and non-linear solvers take so long to solve each time step?
2. Albany is able to solve for the first few time steps (shown in `results.exo` in the zip). What is special about the last one that is causing the failure?
3. Any recommendations on knobs to twist in the input file? Especially for the preconditioner, linear, and non-linear solvers?

For completeness, I'm running this problem with the command:
```
mpirun -n 1 <Albany_root>/build/src/Albany input.yaml 2>&1 | tee output.txt
```
with an version of Albany built on this commit: 3386cd5a3b16cf697b000f7b8b4e72b219b67ab9
and Trilinos built on this commit: https://github.com/trilinos/Trilinos/commit/2213cc0eec527f7cafa18686efde172cf56a06df

Zip with the mentioned files:
[creep_issue_files.zip](https://github.com/SNLComputation/Albany/files/3843666/creep_issue_files.zip)

Let me know if I can give any more information about my problem to help!

**Comment by lxmota** [comment] 2019-11-14 00:09
@JustinClough I'm not sure why you see these issues, as I have not used the creep model myself. But I can definitely say that you want to change a number of things in how you are solving this. In my experience, problems that look deceptively simple are very hard to solve when one deals with any nonlinear regime. I have modified a number of things to your input file that I attach. I can't run it though, because I don't compile with the SCOREC tools.

To start, you most definitely want to use adaptive time stepping. Also, you want to use a backtracking line search in the Newton solver. You also want to use MueLu as a preconditioner instead of Ifpack2. MueLu is takes forever to compile, but it's faster and more robust than Ifpack2.

In addition, you want to use a more complex convergence criterion with adaptive time stepping. You want to let the nonlinear solver fail rather quickly if it's having a hard time, so that the time step is reduced to try again. Check the attached input file to see if my changes are reasonable, and see if you have better luck with these settings.

[input.yaml.txt](https://github.com/SNLComputation/Albany/files/3844016/input.yaml.txt)

**Comment by ikalash** [comment] 2019-11-14 00:55
@lxmota : at the meeting yesterday, I was suggesting @JustinClough run the problem with the linear elastic material model (as a sanity check), perhaps with Dan's 'Single Step' solver (instead of the usual 'Newton-Based' solver) in NOX, since this solver is for linear problems.  Do you think this is worth trying?  I asked Justin also if he's using SDBCs or DBCs, and it's the former so hopefully there isn't weirdness coming from the BCs.  If the problem is supposed to be easy, I wonder if something is off about how it's specified in Albany.  I thought dumping a matrix and looking at it would be helpful too.

**Comment by ikalash** [comment] 2019-11-14 00:56
@JustinClough : I build SCOREC so I should be able to run your case - I'll do that and see if I spot anything that's off, as promised.

**Comment by lxmota** [comment] 2019-11-14 00:59
@ikalash Maybe not the linear elastic case, because it's too different in this case. But definitely a non-creep model like neohookean. First without thermal expansion and then with it to check that things are working OK.

**Comment by ikalash** [comment] 2019-11-14 01:08
Ah ok, makes sense.  @JustinClough could you try Neohookean for the test case to see what happens?  You'd have to keep the solver as is ('Line Search Based') since Neohookean is a nonlinear material model.

**Comment by JustinClough** [comment] 2019-12-02 19:09
Thanks for the help everyone. After trying the above and a few other things, I actually found that my convergence issue is due to the panel buckling. 

I think I need to use an Arc Length method-based stepper. I found one example [here](https://github.com/SNLComputation/Albany/blob/master/tests/small/ContinuationHeat1D/input.yaml#L38) but was wondering if there is anything else I should look at. 

I'll change this issue's title in a moment to reflect the change to buckling.

**Comment by ikalash** [comment] 2019-12-02 20:04
@JustinClough : great to hear that you figured it out!  I was still intending to look at this after the Thanksgiving holiday, but it looks like you beat me to it.  

The input file you pointed me to looks reasonable.  I am not too familiar with all the Arc Length continuation options, e.g. what 'Quadratic Nonlinear Factor' does, and what are the other options.  @etphipp would be able to help you figure out what parameters are reasonable for you to use.

**Comment by etphipp** [comment] 2019-12-02 20:13
The referenced input file includes a quadratic nonlinear source term:  alpha * u^2 where u is the PDE solution.  "Quadratic Nonlinear Factor" is alpha.  You would use some other parameter as your continuation parameter based on your problem.  Apart from parameter ranges, the defaults should be reasonable, but I can help if you run into trouble.

**Comment by JustinClough** [comment] 2019-12-02 22:44
Okay, good to know. I just started a simulation using `Arc Length` and a continuation parameter with `Time`. I'll post back here with how it goes.

**Comment by ikalash** [comment] 2020-07-07 22:44
This is no longer relevant to master, therefore closing.  @JustinClough , feel free to reopen in the SCOREC fork if it's still relevant there.

**Closed by ikalash** 2020-07-07 22:44 UTC
Labels: LCM, question
