### ISSUE TITLE
Clean up dashboards

### ISSUE THREAD

**Issue by ibaned** [SNLComputation/Albany#61] opened 2017-02-07 16:07 UTC
We need to get our dashboards to the all-green point. The public dashboard is here:

http://my.cdash.org/index.php?project=Albany&date=

And today it looks quite green, but I think this is misleading (see #62).

**Comment by ikalash** [comment] 2017-02-07 17:46
@gahansen : Has the external (non-SRN) CDash site license expired?  I noticed some of my projects were not being pushed to this site, and when I log in, I get the following message.

The license for the project Albany has expired.Upgrade Now
* The project Albany has reached the maximum daily upload quota. You should upgrade to a premium account to avoid missing builds.Upgrade Now
* The project HOMMEXX has reached the maximum daily upload quota. You should upgrade to a premium account to avoid missing builds.Upgrade Now

**Comment by gahansen** [comment] 2017-04-21 16:12
I have done some recent work to clean up the Intel test scripts on CEE - 3 or 4 recent commits were directed at this. @mperego  and @bartgol  took a look at failing FELIX Intel tests. @mperego found a fairly serious bug as a result, which was fixed in commit:

60ebdefac7cc06d472fd6445699f5ad80e60c7b2

I wanted to highlight this success as an example of the possibility that failing tests might be pointing at significant (possibly unknown) issues.

**Comment by gahansen** [comment] 2017-04-21 16:15
@ikalash - are you still seeing external CDash issues? Kitware upgraded our project so these issues should be fixed at this point.

**Comment by gahansen** [comment] 2017-07-18 20:09
Closing - this issue is essentially a duplicate of #135 and that one has the most recent activity.

**Comment by bartgol** [comment] 2018-11-28 15:34
The 0erge 6f `thyra_refactor_phase_2` may have increased the red in the cdash. I already pushed one bug fix. In the next few days, I'll keep an eye on it, for errors that look related to that merge.

**Comment by bartgol** [comment] 2018-11-28 15:37
Some tests fails are bizarre though. Take [this one](http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4102242&build=78684), for instance: it says 0 comparisons failed, and yet, one MPI rank has a non-zero exit code. My only guess is that there is probably some resources that are not freed in the correct way (like memory pointers). For some reason it does not happen on rank 0, so we don't see the error in the log.

**Comment by ikalash** [comment] 2018-11-28 19:36
@bartgol : I know, I noticed this.  Unfortunately for Albany (but perhaps fortunately for me :)) this does not happen in builds that I own.  We should discuss cleaning up the dashboard at the next Albany meeting (I will be on finally).

**Comment by bartgol** [comment] 2018-12-04 00:12
The merge or  #356 was responsible of a few failures. I fixed a few in the next thyra branch, which will go in with #396 . Others still fail, but I think they are unrelated to the thyra work (e.g., the test `Dynamics` fails with message `Underlying model in trapezoid decorator does not cast to a Piro::TransientDecorator<Scalar, LocalOrdinal, GlobalOrdinal, Node>`).

**Comment by bartgol** [comment] 2018-12-04 18:53
Should we close this, now that we have a more recent one?

**Comment by ikalash** [comment] 2018-12-04 19:20
Closing in favor of newer issue #398.

**Closed** 2019-03-06 16:11 UTC
Labels: infrastructure
