### ISSUE TITLE
undefined reference to PHAL::ScatterSideEqnResidualBase and a few test failures on debug builds

### ISSUE THREAD

**Issue by jewatkins** [SNLComputation/Albany#611] opened 2020-07-16 15:45 UTC
It looks like there's some linking errors on skybridge and blake:
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=3939
and some test failures on some debug builds:
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3951

@bartgol this probably has to do with the PR you pushed yesterday, correct?

**Comment by bartgol** [comment] 2020-07-16 15:51
Yes, it is definitely that. I'll push some quick fix straight to master, if that's ok.

**Comment by mperego** [comment] 2020-07-16 15:53
Thanks @bartgol . Is the error in debug mode easy to fix? it seems it has to do with how the mesh is decomposed..

**Comment by bartgol** [comment] 2020-07-16 16:35
I haven't looked at the debug error (and I had to disconnect from vpn for a telecon, so I can't look at it now). Will check that in a few minutes.

**Comment by bartgol** [comment] 2020-07-16 22:10
The debug error is strange. It is basically saying that there is a node in the owned map that is not coupled with any other node in the owned map. That is bizarre to say the least. Obviously, something must be going wrong when retrieving gids, either when building the maps, or when creating the graph. It will take some time to debug, I'm afraid. I'll try to fix it, but since I'm off tomorrow, it might slip to early next week.

**Comment by mperego** [comment] 2020-07-16 23:06
Are we sure that seacas decomp tool prevent that from happening? (it was happening with MPAS mehses.. and I had to fix that).

**Comment by bartgol** [comment] 2020-07-17 03:02
What do you mean? I am able to reproduce the error (for some of those tests) on blake, and I have decomp tools compiled in trilinos on both blake and my laptop (where no errors happen).

**Comment by mperego** [comment] 2020-07-17 03:09
I can reproduce that on my workstation  in debug as well.
I'm wondering whether that's a real bug, or simply a "weird" decomposition where there's triangle  owned by a proc but none of  the triangle's vertices is owned by that proc.

**Comment by bartgol** [comment] 2020-07-17 03:14
Uhm, if that's the case, maybe we should build our nodal maps not by asking the node buckets to stk, but asking for the element buckets, then loop over all of them and extract the nodes (which is what we do when we do assembly).

**Comment by ikalash** [comment] 2020-07-20 18:09
Any update on this issue @bartgol ?

**Comment by bartgol** [comment] 2020-07-20 19:36
Not yet. I had other stuff to do in the morning, and I'm currently working on it now.

**Comment by ikalash** [comment] 2020-07-20 19:37
No worries - thanks, Luca!

**Comment by bartgol** [comment] 2020-07-20 22:39
Ok, I was able to reproduce on my workstation with intel compilers. I have to debug over vpn, so it is a bit slow (it lags a bit), but hopefully can find out something by the end of the day.

**Comment by bartgol** [comment] 2020-07-20 23:56
Ok, I printed what is going on, and I think I found the culprit. Tpetra checks that each element in the column map is a column index of at least one row (meaning that if it is in your column map, you must need it). However it checks only the rows of the owned graph, which is not the right thing.

I'm going to open an issue in Trilinos.

**Comment by mperego** [comment] 2020-07-21 00:08
@bartgol this is a good story on how we help maturing Trilinos!

**Comment by bartgol** [comment] 2020-07-21 03:41
I'm actually having second thoughts. I _do_ believe something is wrong in Trilinos, but I am not 100% sure, nor I can fully explain why. I need to get more clarity before I can open an issue in Trilinos and/or fix it.

**Comment by bartgol** [comment] 2020-07-21 06:18
So I concluded that the problem is not with Tpetra, but more likely, as Mauro foresaw, in how we partition the mesh.

Turns out that there is a cell where ALL the nodes are NOT in the owned map. Some of them also appear in other cells, where at least one node is _owned_, so for those nodes the Tpetra test passes (those nodes are col indices of at least one row that is owned). However, there is one node in that cell that does not appear in any other cell. So for that node, there is no _owned_ row that lists it as a col index.

This is quite confusing cause either we are completely messing up something when extracting the stk entities (either at the time where we build maps or at the time where we build the graph) or something goes awfully wrong during the decomposition phase. It might be the former, since there is a _tiny_ difference: when we build vector spaces, we use `metaData.locally_owned_part()` as node selector, while with the graph we use that and-ed with `metaData.universal_part()`. I am not sure why that would mess us up, since I assume universal part is a superset of basically anything else (so and-ing those parts should yield the same selector as in the node case), but I might check that too.

This bug is nasty. The puzzling (but perhaps important) detail is that I _did_ try a debug build on my laptop before we merged the PR and everything was passing. Now I rebuilt trilinos and albany, tried again, and finally the bug showed up. I am wondering whether something changed in Trilinos. A quick git log showed not much changed in Tpetra (at least not stuff that seems to impact our use case). However, there might have been changes in stk. I'm trying to parse trilinos git tree but I'm too tired, and I should probably go to bed.

**Comment by bartgol** [comment] 2020-07-21 06:36
Coming to think of it, what we're observing should be quite common: if you have an unstructured triangular mesh, positioning it would likely yield a zigzagged edge. Having a triangle with all nodes ghosted is then not unlikely.

This brings me back to my original thought: trilinos should not perform this check.

**Comment by mperego** [comment] 2020-07-21 15:33
@bartgol the  zigzagged partitioning happend in MPAS. Worse than that we had a situation were a proc would own only one triangle but no nodes at all. MueLu didn't like that and I had to fix the way we partioned the mesh in the MPAS interface. It' wuld be a pain to do the same in Albany. 
Solvers seem to do fine with standalone Albany, so maybe the check done in FE Crs Matrix is too strict?

Anyway, we shoud probably shoot an email to the  solver guys (C. Siefert, J. Hu, R. Tuminaro, Luc and Christian).
B.t..w you did not change the ownership for nodes and elements, when you did the FE Crs refactor, right? It's Seacas that decides the ownership, right?

**Comment by bartgol** [comment] 2020-07-21 15:36
Correct. I changed the way we "order" the GIDs in our overlap map (not the owned), but not how the entities are distributed among ranks.

I can open an issue in Trilinos, since what the check is actually doing is not what the error message says anyways. We can then take it from there.

**Comment by mperego** [comment] 2020-07-22 21:17
@ikalash there are a few PRs lininig up, and it's a bit of a problem that the debug build fails because of the Tpetra FE matrix check.  Would it be possible to temperarily freeze the version of Trilinos we use for the debug builds and fix it to disable the Tpetra FE Matrix check? In this way we can keep checking Albany code in debug mode.

**Comment by bartgol** [comment] 2020-07-22 21:57
@mperego , we would need to clone a different trilinos branch in all of our nightlies.

Maybe a proposal: should Albany keep a fork of Trilinos, and use this fork for testing? We can put this kind of hot fixes relatively quickly in our fork. We could even add some jenkins job that automatically perform a merge of Trilinos develop into our fork every night, to make sure we're always caught up.

**Comment by mperego** [comment] 2020-07-22 22:08
Well, that's what Ross Bartlett would recommend, and it's what ATDM does, but it is extra work.. not sure it's worth for a relatively small application like Albany.

**Comment by bartgol** [comment] 2020-07-22 23:47
Well, how often do we wait for fixes/branches to get into trilinos? Setting up a jenkins job that simply does an upstream merge, should not be that hard.

**Comment by mperego** [comment] 2020-07-23 00:05
Before an upstream merge you would have to check whether the merge breaks any Albany build/tests. That's not that easy to automatize and it's enough to have one failing test (not due to Trilinos) in Albany to hold the merge. ATDM is a larger projects and it has way more nightly builds than we do but it takes half of Ross time to keep the merging process flowing and tomonitor/triage the nightly builds (the latter is similar to what Irina does for Albany).

**Comment by ikalash** [comment] 2020-07-23 00:23
> @ikalash there are a few PRs lininig up, and it's a bit of a problem that the debug build fails because of the Tpetra FE matrix check. Would it be possible to temperarily freeze the version of Trilinos we use for the debug builds and fix it to disable the Tpetra FE Matrix check? In this way we can keep checking Albany code in debug mode.

Yes, I can do this.  Would you like me to?  What is a good tag to use from Trilinos develop branch?

My two cents: I have also talked with Ross about having a special fork of Trilinos for Albany and my opinion is that this is not worth the effort...  but there are certainly arguments for doing it, as you guys discuss above.

**Comment by mperego** [comment] 2020-07-23 00:34
> > @ikalash there are a few PRs lininig up, and it's a bit of a problem that the debug build fails because of the Tpetra FE matrix check. Would it be possible to temperarily freeze the version of Trilinos we use for the debug builds and fix it to disable the Tpetra FE Matrix check? In this way we can keep checking Albany code in debug mode.
> 
> Yes, I can do this. Would you like me to? What is a good tag to use from Trilinos develop branch?

That be great, at least for one of the debug builds. I think you can use the Trilinos develop head, and then you have to comment out these lines
https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp#L273-L292
to disable the check.

**Comment by ikalash** [comment] 2020-07-28 15:45
@mperego: I finally have this patch up on the CEE debug nightlies.  Sorry about the delay.  I wrote the patch at the beginning of last week but due to some CEE nightly testing idiosyncrasies, the patch didn't start getting applied correctly until today.  

There are still 3 failures in these builds:

```

FO_GIS_Analysis_StiffeningBasalFriction 
SteadyHeatConstrainedOpt2D_Dirichlet_Dist_Param_Analysis
SteadyHeatConstrainedOpt2D_Dirichlet_Mixed_Params_Analysis_Tpetra

```

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=4355
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=4356

Could you please look at them?  The latter 2 are new - could they be from @kliegeois 's PR merge yesterday?  

Also, I don't think this patch should be a long term solution for things to run clean in the CEE debug builds.  I assume there is a plan to get the patch (or some other fix) into Trilinos master at some point in the near future?

**Comment by mperego** [comment] 2020-07-28 15:51
Great, Thanks! I'll have a look at them.
Yeah, Luca is trying to convince Chris Siefert to modify that check.. but Chris is not very responsive... I'll ping him again today.

**Comment by ikalash** [comment] 2020-07-28 15:53
Thanks, Mauro!  That's good that you guys are making strides to get the fix in master.  It's OK as is for some time; I just don't want to forget about it.

**Comment by bartgol** [comment] 2020-07-28 16:42
> Great, Thanks! I'll have a look at them.
> Yeah, Luca is trying to convince Chris Siefert to modify that check.. but Chris is not very responsive... I'll ping him again today.

He replied today. But I'm leaving for vacation in 3...2...1... So I can only work on it on Monday. Feel free to take a stab at it however... ;)

**Comment by mperego** [comment] 2020-07-28 16:54
@bartgol enjoy your vacation... we'll be good until next week.. and I don't want to deprive you of the honor of fixing that debug check! :-)

**Comment by bartgol** [comment] 2020-08-03 17:55
@mperego How nice of you! =D

**Comment by bartgol** [comment] 2021-03-11 18:46
The link error was fixed, and IIRC the bug with the node ownership was fixed when we added a ctor to Tpetra::FECrsGraph in trilinos. Closing.

**Closed by bartgol** 2021-03-11 18:46 UTC
Labels: Testing
